name: Publish HTML report to gh-pages with age retention
description: "Publish an HTML report directory into a gh-pages branch and prune old reports."
inputs:
  report_path:
    description: "Path (in caller workspace) to generated HTML report directory"
    required: true
  retention_days:
    description: "Delete reports older than this many days (-1 keeps all reports)"
    required: false
    default: 30
  reports_dir:
    description: "Directory inside gh-pages where reports are stored"
    required: false
    default: reports
  pages_branch:
    description: "Pages branch"
    required: false
    default: gh-pages
  artifact_name:
    description: "Optional: download this artifact instead of using local report_path"
    required: false
    default: ""
outputs:
  report_url:
    description: "URL to the published report (pages site)"
    value: ${{ steps.set_output.outputs.report_url }}

runs:
  using: "composite"
  steps:
    - name: Download artifact (optional)
      if: ${{ inputs.artifact_name != '' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.report_path }}

    - name: Validate report path
      shell: bash
      run: |
        set -euo pipefail
        if [ ! -d "${{ inputs.report_path }}" ]; then
          echo "Report directory not found: ${{ inputs.report_path }}"
          exit 1
        fi
        # Allow -1 to indicate "keep all reports"; otherwise must be a non-negative integer
        if ! [[ "${{ inputs.retention_days }}" =~ ^-?[0-9]+$ ]]; then
          echo "retention_days must be an integer (use -1 to keep all): ${{ inputs.retention_days }}"
          exit 1
        fi
        if [[ "${{ inputs.retention_days }}" =~ ^- ]] && [ "${{ inputs.retention_days }}" != "-1" ]; then
          echo "Only -1 is supported as a negative value to keep all reports: ${{ inputs.retention_days }}"
          exit 1
        fi

        reports_dir="${{ inputs.reports_dir }}"
        if [ -z "$reports_dir" ]; then
          echo "reports_dir cannot be empty"
          exit 1
        fi
        if ! [[ "$reports_dir" =~ ^[A-Za-z0-9._/-]+$ ]]; then
          echo "reports_dir contains invalid characters: $reports_dir"
          exit 1
        fi
        if [[ "$reports_dir" == /* || "$reports_dir" == *".."* || "$reports_dir" == *"//"* ]]; then
          echo "reports_dir must be a safe relative path without traversal: $reports_dir"
          exit 1
        fi

        pages_branch="${{ inputs.pages_branch }}"
        if [ -z "$pages_branch" ]; then
          echo "pages_branch cannot be empty"
          exit 1
        fi
        if ! [[ "$pages_branch" =~ ^[A-Za-z0-9._/-]+$ ]]; then
          echo "pages_branch contains invalid characters: $pages_branch"
          exit 1
        fi
        if [[ "$pages_branch" == /* || "$pages_branch" == *".."* || "$pages_branch" == *"//"* ]]; then
          echo "pages_branch must be a safe git ref name: $pages_branch"
          exit 1
        fi

    - name: Checkout pages branch
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.pages_branch }}
        path: pages
        fetch-depth: 0
      continue-on-error: true

    - name: Initialize pages branch if needed
      shell: bash
      run: |
        set -euo pipefail
        if [ ! -d pages/.git ]; then
          echo "Failed to prepare pages repository checkout"
          exit 1
        fi

        cd pages
        branch="${{ inputs.pages_branch }}"
        if git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
          git fetch --depth=1 origin "$branch"
          git checkout -B "$branch" "origin/$branch"
        else
          git checkout --orphan "$branch"
          git rm -rf . || true
          mkdir -p "${{ inputs.reports_dir }}"
          touch .nojekyll
          printf '%s\n' "<!doctype html><html><body><h1>Test Reports</h1></body></html>" > index.html
        fi

    - name: Publish report
      id: publish_report
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "pages/${{ inputs.reports_dir }}"
        touch pages/.nojekyll
        ts="$(date -u +'%Y-%m-%dT%H-%M-%SZ')"
        dest="${ts}-run-${GITHUB_RUN_ID}"
        mkdir -p "pages/${{ inputs.reports_dir }}/${dest}"
        cp -R "${{ inputs.report_path }}/." "pages/${{ inputs.reports_dir }}/${dest}/"

        rm -rf pages/latest
        ln -s "${{ inputs.reports_dir }}/${dest}" pages/latest || true
        echo "dest=${dest}" >> $GITHUB_OUTPUT
        echo "relative_path=${{ inputs.reports_dir }}/${dest}" >> $GITHUB_OUTPUT

    - name: Prune old reports
      shell: bash
      run: |
        set -euo pipefail
        if [ "${{ inputs.retention_days }}" = "-1" ]; then
          echo "Retention set to -1; keeping all reports (no pruning)"
        else
          now="$(date -u +%s)"
          max_age="$(( ${{ inputs.retention_days }} * 24 * 60 * 60 ))"
          shopt -s nullglob
          for dir in pages/${{ inputs.reports_dir }}/*; do
            [ -d "$dir" ] || continue
            base="$(basename "$dir")"
            ts="${base%-run-*}"
            if epoch="$(date -u -d "${ts//T/ }" +%s 2>/dev/null)"; then
              age="$(( now - epoch ))"
              if [ "$age" -gt "$max_age" ]; then
                rm -rf "$dir"
              fi
            fi
          done
        fi

    - name: Rebuild index
      shell: bash
      run: |
        set -euo pipefail

        html_escape() {
          local value="$1"
          value="${value//&/&amp;}"
          value="${value//</&lt;}"
          value="${value//>/&gt;}"
          value="${value//\"/&quot;}"
          value="${value//\'/&#39;}"
          printf '%s' "$value"
        }

        shopt -s nullglob
        report_dirs=()
        for path in "pages/${{ inputs.reports_dir }}"/*; do
          [ -d "$path" ] || continue
          report_dirs+=("$(basename "$path")")
        done

        reports_dir_safe="$(html_escape "${{ inputs.reports_dir }}")"

        {
          echo "<!doctype html><html><head><meta charset='utf-8'><title>Test Reports</title></head><body>"
          echo "<h1>Test Reports</h1>"
          if [ "${{ inputs.retention_days }}" = "-1" ]; then
            echo "<p>Retention: keep all reports</p>"
          else
            echo "<p>Retention: ${{ inputs.retention_days }} day(s)</p>"
          fi
          echo "<ul>"
          if [ "${#report_dirs[@]}" -gt 0 ]; then
            while IFS= read -r d; do
              d_safe="$(html_escape "$d")"
              echo "<li><a href=\"${reports_dir_safe}/${d_safe}/\">${d_safe}</a></li>"
            done < <(printf '%s\n' "${report_dirs[@]}" | sort -r)
          fi
          echo "</ul><p><a href=\"latest/\">Latest report</a></p></body></html>"
        } > pages/index.html

    - name: Commit and push
      shell: bash
      run: |
        set -euo pipefail
        cd pages
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        branch="${{ inputs.pages_branch }}"
        if git rev-parse --verify "$branch" >/dev/null 2>&1; then
          git checkout "$branch"
        else
          git checkout --orphan "$branch" || git checkout -b "$branch"
          git rm -rf . || true
        fi

        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        git commit -m "Publish report for run ${GITHUB_RUN_ID}"
        git push --set-upstream origin "$branch"

    - name: Set action output
      id: set_output
      shell: bash
      run: |
        echo "report_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ steps.publish_report.outputs.relative_path }}/" >> $GITHUB_OUTPUT

