name: Publish HTML report to gh-pages with age retention
description: "Publish an HTML report directory into a gh-pages branch and prune old reports."
inputs:
  report_path:
    description: "Path (in caller workspace) to generated HTML report directory"
    required: true
  retention_days:
    description: "Delete reports older than this many days"
    required: false
    default: 30
  reports_dir:
    description: "Directory inside gh-pages where reports are stored"
    required: false
    default: reports
  pages_branch:
    description: "Pages branch"
    required: false
    default: gh-pages
  artifact_name:
    description: "Optional: download this artifact instead of using local report_path"
    required: false
    default: ""
outputs:
  report_url:
    description: "URL to the published report (pages site)"

runs:
  using: "composite"
  steps:
    - name: Download artifact (optional)
      if: ${{ inputs.artifact_name != '' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.report_path }}

    - name: Validate report path
      shell: bash
      run: |
        set -euo pipefail
        if [ ! -d "${{ inputs.report_path }}" ]; then
          echo "Report directory not found: ${{ inputs.report_path }}"
          exit 1
        fi

    - name: Checkout pages branch
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.pages_branch }}
        path: pages
      continue-on-error: true

    - name: Initialize pages branch if needed
      shell: bash
      run: |
        set -euo pipefail
        if [ ! -d pages/.git ]; then
          git clone --no-checkout "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" pages
          cd pages
          git checkout --orphan "${{ inputs.pages_branch }}"
          git rm -rf . || true
          mkdir -p "${{ inputs.reports_dir }}"
          printf '%s\n' "<!doctype html><html><body><h1>Test Reports</h1></body></html>" > index.html
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Initialize ${{ inputs.pages_branch }}"
          git push origin "${{ inputs.pages_branch }}"
          cd ..
        fi

    - name: Publish report
      id: publish_report
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "pages/${{ inputs.reports_dir }}"
        ts="$(date -u +'%Y-%m-%dT%H-%M-%SZ')"
        dest="${ts}-run-${GITHUB_RUN_ID}"
        mkdir -p "pages/${{ inputs.reports_dir }}/${dest}"
        cp -R "${{ inputs.report_path }}/." "pages/${{ inputs.reports_dir }}/${dest}/"

        rm -rf pages/latest
        ln -s "${{ inputs.reports_dir }}/${dest}" pages/latest || true
        echo "dest=${dest}" >> $GITHUB_OUTPUT
        echo "relative_path=${{ inputs.reports_dir }}/${dest}" >> $GITHUB_OUTPUT

    - name: Set action output
      shell: bash
      run: |
        echo "report_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ steps.publish_report.outputs.relative_path }}/" >> $GITHUB_OUTPUT

    - name: Prune old reports
      shell: bash
      run: |
        set -euo pipefail
        now="$(date -u +%s)"
        max_age="$(( ${{ inputs.retention_days }} * 24 * 60 * 60 ))"
        shopt -s nullglob
        for dir in pages/${{ inputs.reports_dir }}/*; do
          [ -d "$dir" ] || continue
          base="$(basename "$dir")"
          ts="${base%-run-*}"
          if epoch="$(date -u -d "${ts//T/ }" +%s 2>/dev/null)"; then
            age="$(( now - epoch ))"
            if [ "$age" -gt "$max_age" ]; then
              rm -rf "$dir"
            fi
          fi
        done

    - name: Rebuild index
      shell: bash
      run: |
        set -euo pipefail
        {
          echo "<!doctype html><html><head><meta charset='utf-8'><title>Test Reports</title></head><body>"
          echo "<h1>Test Reports</h1>"
          echo "<p>Retention: ${{ inputs.retention_days }} day(s)</p>"
          echo "<ul>"
          for d in $(ls -1 "pages/${{ inputs.reports_dir }}" 2>/dev/null | sort -r); do
            echo "<li><a href=\"${{ inputs.reports_dir }}/${d}/\">${d}</a></li>"
          done
          echo "</ul><p><a href=\"latest/\">Latest report</a></p></body></html>"
        } > pages/index.html

    - name: Commit and push
      shell: bash
      run: |
        set -euo pipefail
        cd pages
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        branch="${{ inputs.pages_branch }}"
        if git rev-parse --verify "$branch" >/dev/null 2>&1; then
          git checkout "$branch"
        else
          git checkout --orphan "$branch" || git checkout -b "$branch"
          git rm -rf . || true
        fi

        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        git commit -m "Publish report for run ${GITHUB_RUN_ID}"
        git push --set-upstream origin "$branch"
